# SPDX-License-Identifier: MIT
---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  yamllint .yamllint.yml .
  ansible-lint
  flake8
platforms:
  - name: centos-7
    image: centos/systemd
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: /usr/sbin/init
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: testinfra
