# SPDX-License-Identifier: MIT
---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  yamllint .yamllint.yml .
  ansible-lint
  flake8
platforms:
  - name: centos-7
    image: docker.io/linuxsystemroles/centos-7
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: testinfra
